
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Logic.Download;
import Logic.Message;
import Logic.SocketClient;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.JTextPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author Thu Tinh
 */
public class GroupChatFrame extends javax.swing.JFrame {

    SocketClient socket;
    Thread thread;
    public String userName;
    public String nameGroup;
    public String choosingItem = "";
    public String lastUser = "";
    public DefaultListModel onlineModel, memberModel;
    public  BoxLayout boxLayout;
    String loai = "file";
     public File file;

    /**
     * Creates new form GroupChatFrame
     */
    public GroupChatFrame(SocketClient socketClient, String user, String name, MainFrame mainFrame) {
        initComponents();
         boxLayout = new BoxLayout(txtChat, BoxLayout.Y_AXIS);
        txtChat.setLayout(boxLayout);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconchat.png")));
        txtMessage.requestFocus();
        txtMessageInfo.setEditable(false);
        this.socket = socketClient;
        this.userName = user;
        this.nameGroup = name;
        super.setResizable(false);
        for (int i = 0; i < mainFrame.model.getSize(); i++) {

            onlineModel.addElement(mainFrame.model.getElementAt(i));
            //JOptionPane.showMessageDialog(null,"Them user"+mainFrame.model.getElementAt(i));
        }
        this.setTitle(nameGroup);
        setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                setVisible(false);
            }
        });

    }

    public JButton getBtnAdd() {
        return btnAdd;
    }

    public JList getLsMember() {
        return lsMember;
    }

    public JList getLsOnline() {
        return lsOnline;
    }

    public JTextField getTxtMessage() {
        return txtMessage;
    }

    public JTextPane getTxtMessageInfo() {
        return txtMessageInfo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMessageInfo = new javax.swing.JTextPane();
        txtMessage = new javax.swing.JTextField();
        btnhistory = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lsOnline = new javax.swing.JList();
        btnAdd = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lsMember = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        btnQuit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        scrollChat = new javax.swing.JScrollPane();
        txtChat = new javax.swing.JPanel();
        btnimage = new javax.swing.JButton();
        btnLink = new javax.swing.JButton();
        btnSend = new javax.swing.JButton();
        nameFile = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(214, 90, 49));

        txtMessageInfo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jScrollPane1.setViewportView(txtMessageInfo);

        txtMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMessageActionPerformed(evt);
            }
        });
        txtMessage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMessageKeyPressed(evt);
            }
        });

        btnhistory.setText("History");
        btnhistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhistoryMouseClicked(evt);
            }
        });
        btnhistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhistoryActionPerformed(evt);
            }
        });

        jLabel1.setText("Online");

        lsOnline.setModel( onlineModel = new DefaultListModel());
        lsOnline.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lsOnlineMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lsOnline);

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        lsMember.setModel(memberModel = new DefaultListModel());
        jScrollPane3.setViewportView(lsMember);

        jLabel2.setText("Members");

        btnQuit.setText("Quit");
        btnQuit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuitMouseClicked(evt);
            }
        });
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });

        scrollChat.setBackground(new java.awt.Color(255, 51, 51));

        txtChat.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout txtChatLayout = new javax.swing.GroupLayout(txtChat);
        txtChat.setLayout(txtChatLayout);
        txtChatLayout.setHorizontalGroup(
            txtChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
        );
        txtChatLayout.setVerticalGroup(
            txtChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 189, Short.MAX_VALUE)
        );

        scrollChat.setViewportView(txtChat);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(scrollChat, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollChat, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        btnimage.setIcon(new javax.swing.ImageIcon("D:\\HK6\\LapTrinhJava\\DoAn\\LanChat\\ClientChat\\img.png")); // NOI18N
        btnimage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimageActionPerformed(evt);
            }
        });

        btnLink.setIcon(new javax.swing.ImageIcon("D:\\HK6\\LapTrinhJava\\DoAn\\LanChat\\ClientChat\\icons8-link-20.png")); // NOI18N
        btnLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLinkActionPerformed(evt);
            }
        });

        btnSend.setIcon(new javax.swing.ImageIcon("D:\\HK6\\LapTrinhJava\\DoAn\\LanChat\\ClientChat\\icons8-upload-20.png")); // NOI18N
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(nameFile)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnimage, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLink, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnhistory))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 44, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAdd)
                                .addGap(10, 10, 10))
                            .addComponent(btnQuit, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdd)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnimage, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnhistory)
                                .addComponent(btnQuit))
                            .addComponent(btnLink, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameFile))
                        .addGap(13, 13, 13)))
                .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMessageActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if (choosingItem != "") {
            socket.send(new Message("AddMemberGroup", userName, choosingItem, nameGroup));
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void lsOnlineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lsOnlineMouseClicked
        // TODO add your handling code here:
        lsOnline = (JList) evt.getSource();
        if (evt.getClickCount() == 1) {
            int index = lsOnline.locationToIndex(evt.getPoint());
            choosingItem = lsOnline.getSelectedValue().toString();
        }
        if (evt.getClickCount() == 2) {
            int index = lsOnline.locationToIndex(evt.getPoint());
            choosingItem = lsOnline.getSelectedValue().toString();
            socket.send(new Message("AddMemberGroup", userName, choosingItem, nameGroup));

        }
    }//GEN-LAST:event_lsOnlineMouseClicked

    private void txtMessageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMessageKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!txtMessage.getText().isEmpty()) {
                String msg = txtMessage.getText();
                //code mới
                JLabel lbChat = new JLabel("Tôi: " + msg);
                lbChat.setForeground(Color.ORANGE);
                txtChat.add(lbChat);
                revalidate();
                socket.send(new Message("GroupChat", userName, msg, nameGroup));
                txtMessage.setText("");

                //code cũ
                StyledDocument doc = txtMessageInfo.getStyledDocument();
                SimpleAttributeSet right = new SimpleAttributeSet();
                StyleConstants.setAlignment(right, StyleConstants.ALIGN_RIGHT);
                Style style = txtMessageInfo.addStyle(null, null);
                StyleConstants.setForeground(style, Color.blue);
                try {
                    String message = msg + "\n";
                    int lenght = doc.getLength();
                    doc.insertString(lenght, message, style);
                    doc.setParagraphAttributes(lenght + 1, 1, right, false);

                } catch (Exception e) {

                }
            }
        }
    }//GEN-LAST:event_txtMessageKeyPressed

    private void btnQuitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuitMouseClicked
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(null, "Do you want to leave group", "Thông tin", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            socket.send(new Message("groupchat-leave", userName, "true", nameGroup));
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnQuitMouseClicked

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        // TODO add your handling code here:
//        socket.send(new Message("groupchat-leave", userName, nameGroup, "SERVER"));
//        this.hide();
    }//GEN-LAST:event_btnQuitActionPerformed

    private void btnhistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhistoryActionPerformed
        // TODO add your handling code here:
        //   socket.send(new Message("GroupChatHistory", userName, nameGroup, "Server"));

    }//GEN-LAST:event_btnhistoryActionPerformed

    private void btnhistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhistoryMouseClicked
        // TODO add your handling code here:
        try {
            socket.send(new Message("GroupChatHistory", userName, nameGroup, "Server"));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Chạy chưa dc nè" + e.toString());
        }

    }//GEN-LAST:event_btnhistoryMouseClicked

    private void btnimageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimageActionPerformed
        // TODO add your handling code here:
        loai = "img";
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Images", "jpg", "png", "gif", "bmp"));
        fileChooser.setAcceptAllFileFilterUsed(false);
        fileChooser.showDialog(this, "Select file");
        file = fileChooser.getSelectedFile();
        nameFile.setText(file.getName());
    }//GEN-LAST:event_btnimageActionPerformed

    private void btnLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLinkActionPerformed
        // TODO add your handling code here:
        loai = "file";
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("PDF Documents", "pdf"));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("MS Office Documents", "docx", "xlsx", "pptx","txt"));
        fileChooser.setAcceptAllFileFilterUsed(false);
        //        FileFilter filter = new FileNameExtensionFilter("Image Files", "jpg", "png", "tif");
        //        fileChooser.addChoosableFileFilter(filter);
        fileChooser.showDialog(this, "Select file");
        file = fileChooser.getSelectedFile();
        nameFile.setText(file.getName());
    }//GEN-LAST:event_btnLinkActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        long size = file.length();
        if (size < 120 * 1024 * 1024) {
            if (loai.equals("img")) {
                JLabel lbuser = new JLabel();
                lbuser.setSize(120, 120);
                JLabel lb = new JLabel("Tôi: ");
                txtChat.add(lb);
                ImageIcon icon = new ImageIcon(new ImageIcon(file.getPath()).getImage().getScaledInstance(120, 120, Image.SCALE_DEFAULT));
                lbuser.setIcon(icon);
                txtChat.add(lbuser);
                lbuser.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        Desktop desktop = Desktop.getDesktop();

                        if (file.exists()) {
                            try {
                                desktop.open(file);
                            } catch (IOException ex) {
                                Logger.getLogger(Download.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                    }
                });
            } else {

                JLabel lbuser = new JLabel( "Tôi: " + file.getName());
                lbuser.setForeground(Color.PINK);
                txtChat.add(lbuser);
                lbuser.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        Desktop desktop = Desktop.getDesktop();
                        if (file.exists()) {
                            try {
                                desktop.open(file);
                            } catch (IOException ex) {
                                Logger.getLogger(Download.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                    }
                });
            }
            revalidate();
             socket.send(new Message("UploadReqGropup", userName, file.getName() + "-" + loai, nameGroup));           
            nameFile.setText("");
        } else {
            //            StyledDocument doc = this.getTxtMessageInfo().getStyledDocument();
            //            SimpleAttributeSet left = new SimpleAttributeSet();
            //            StyleConstants.setAlignment(left, StyleConstants.ALIGN_CENTER);
            //            Style style = this.getTxtMessageInfo().addStyle(null, null);
            //            StyleConstants.setForeground(style, Color.MAGENTA);
            //            String message = "File quá lớn!" + "\n";
            //            try {
                //                int length = doc.getLength();
                //                doc.insertString(doc.getLength(), message, style);
                //                doc.setParagraphAttributes(length + 1, 1, left, false);
                //            } catch (Exception e) {
                //                System.out.println(e);
                //            }
            JOptionPane.showMessageDialog(this, "File quá lớn!!");
        }
    }//GEN-LAST:event_btnSendActionPerformed

    public void AddMember(String name) {
        this.memberModel.addElement(name);
    }

    public void MoveUserFromUserToMemberModel(String name) {
        for (int i = 0; i < onlineModel.getSize(); i++) {
            if (onlineModel.getElementAt(i).equals(name)) {
                onlineModel.removeElementAt(i);
                AddMember(name);
                break;
            }

        }
    }

    public JPanel getTxtChat() {
        return txtChat;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnLink;
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnhistory;
    private javax.swing.JButton btnimage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList lsMember;
    private javax.swing.JList lsOnline;
    private javax.swing.JTextField nameFile;
    private javax.swing.JScrollPane scrollChat;
    private javax.swing.JPanel txtChat;
    private javax.swing.JTextField txtMessage;
    private javax.swing.JTextPane txtMessageInfo;
    // End of variables declaration//GEN-END:variables

    public void MoveUserFromUserToAddModel(String name) {
        for (int i = 0; i < memberModel.getSize(); i++) {
            if (memberModel.getElementAt(i).equals(name)) {
                memberModel.removeElementAt(i);
                onlineModel.addElement(name);
                break;
            }
        }
    }
}
