/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JTextPane;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author Thu Tinh
 */
public class HistoryFrame extends javax.swing.JFrame {

    public  String user="";
    public  String taget="";
    public  String groupName="";
    /**
     * Creates new form HistoryChat
     */
    
    
     public HistoryFrame(String sender, String receipient) {
        this.user = sender;
        this.taget = receipient;
        initComponents();
        this.setVisible(true);
        this.txtHistory.setEditable(false);
        super.setResizable(false);
        //lblName.setText(target);
        setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                txtHistory.setText("");
                setVisible(false);
            }
        });
    }
     
    public HistoryFrame(String user, String groupname, String empty) {
       this.user = user;
       this.groupName = groupname;
        initComponents();
        this.setVisible(true);
        this.txtHistory.setEditable(false);
        this.setTitle("History");
         setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                txtHistory.setText("");
                setVisible(false);
            }
        });
    }

    public String getUser() {
        return user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public String getTaget() {
        return taget;
    }

    public void setTaget(String taget) {
        this.taget = taget;
    }

    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtHistory = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(txtHistory);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 323, 278));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   
    public JTextPane getTxtHistory()
    {
        return txtHistory;
    }
    public  void AddMessage(String sender, String resiver , String content )
    {
        // String arr[] = content.split("/");
        if(sender.equals(user)&&resiver.equals(taget))
        {
            StyledDocument doc = txtHistory.getStyledDocument();
            SimpleAttributeSet right = new SimpleAttributeSet();
            StyleConstants.setAlignment(right, StyleConstants.ALIGN_RIGHT);
            Style style = txtHistory.addStyle(null, null);
            StyleConstants.setForeground(style, Color.blue);
           
            try {
               
                        
                int length = doc.getLength();
//                 doc.insertString(doc.getLength(),arr[0]+": ", style);
                 doc.insertString(doc.getLength(),content+"\n", style);
                doc.setParagraphAttributes(length+1, 1, right, false);
            }
            catch(Exception e) {
                System.out.println(e);
            }
        }
        else
        {
            if (sender.equals(taget) && resiver.equals(user)){
            StyledDocument doc = txtHistory.getStyledDocument();
            SimpleAttributeSet left = new SimpleAttributeSet();
            StyleConstants.setAlignment(left, StyleConstants.ALIGN_LEFT);
            Style style = txtHistory.addStyle(null, null);
            StyleConstants.setForeground(style, Color.black);
            
            try {
                int length = doc.getLength();
//                 doc.insertString(doc.getLength(),arr[0]+": ", style);
                  doc.insertString(doc.getLength(),content+"\n", style);
                doc.setParagraphAttributes(length+1, 1, left, false);
            }
            catch(Exception e) {
                System.out.println(e);
            }
        }
        }
        
    }
    
       public void AddGroupMessage(String sender, String groupName, String content){
        String temp_sender = "";
        if (groupName.equals(this.groupName) && sender.equals(this.user)){
            StyledDocument doc = txtHistory.getStyledDocument();
            SimpleAttributeSet left = new SimpleAttributeSet();
            StyleConstants.setAlignment(left, StyleConstants.ALIGN_RIGHT);
            Style style = txtHistory.addStyle(null, null);
            StyleConstants.setForeground(style, Color.BLUE);
            String message = content + "\n";
            try {
                int length = doc.getLength();
                doc.insertString(doc.getLength(), message, style);
                doc.setParagraphAttributes(length+1, 1, left, false);
            }
            catch(Exception e) {
                System.out.println(e);
            }
        }
        else if (groupName.equals(this.groupName) && !sender.equals(this.user)){
            if (!sender.equals(temp_sender)){
                temp_sender = sender;
                StyledDocument doc = txtHistory.getStyledDocument();
                SimpleAttributeSet left = new SimpleAttributeSet();
                StyleConstants.setAlignment(left, StyleConstants.ALIGN_LEFT);
                Style style = txtHistory.addStyle(null, null);
                StyleConstants.setForeground(style, Color.PINK);
                String message = sender + " said:\n";
                try {
                    int length = doc.getLength();
                    doc.insertString(doc.getLength(), message, style);
                    doc.setParagraphAttributes(length+1, 1, left, false);
                }
                catch(Exception e) {
                    System.out.println(e);
                }
            }
            StyledDocument doc = txtHistory.getStyledDocument();
            SimpleAttributeSet left = new SimpleAttributeSet();
            StyleConstants.setAlignment(left, StyleConstants.ALIGN_LEFT);
            Style style = txtHistory.addStyle(null, null);
            StyleConstants.setForeground(style, Color.black);
            String message = content + "\n";
            try {
                int length = doc.getLength();
                doc.insertString(doc.getLength(), message, style);
                doc.setParagraphAttributes(length+1, 1, left, false);
            }
            catch(Exception e) {
                System.out.println(e);
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane txtHistory;
    // End of variables declaration//GEN-END:variables
}
